### ISSUE TITLE
Error using level-sublevel@6

### ISSUE THREAD

**Issue by vanvuongngo** [levelgraph/levelgraph#184]
```
  "dependencies": {
    "level": "^4.0.0",
    "level-browserify": "^2.0.0",
    "level-sublevel": "^6.6.5",
    "levelgraph": "^2.1.1",
    "levelup": "^4.0.0"
  }
```
Crashes with an error when call ```.get```. Works with level-sublevel@5:
```
var levelup = require("level");
var sublevel = require("level-sublevel");
var levelgraph = require("levelgraph");
var db = sublevel(levelup("yourdb"));
var graph = levelgraph(db.sublevel('graph'));

const triple = { subject: "a", predicate: "b", object: "c" };

graph.put(triple, (err) => {
  graph.get({ subject: "a" }, (err, list) => {
    console.log('Error', err);
    console.log(list);
    db.close();
  });
});

```

outputs:
```
EncodingError: Unexpected token o in JSON at position 1
    at /node_modules/level-sublevel/node_modules/levelup/lib/read-stream.js:60:28
    at /node_modules/abstract-leveldown/abstract-iterator.js:29:14
    at /node_modules/encoding-down/index.js:126:5
    at /node_modules/abstract-leveldown/abstract-iterator.js:29:14
    at /node_modules/leveldown/iterator.js:46:7
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

**Comment by neatfx** [comment]
```javascript
var db = sublevel(levelup("yourdb", {
  valueEncoding: 'json'
}))
```

**Comment by vanvuongngo** [comment]
@neatfx, thank you very much and your solution works pretty good.
