### ISSUE TITLE
does not work with persistent level db 

### ISSUE THREAD

**Issue by scenaristeur** [levelgraph/levelgraph#197]
```
  a basic triple store
    ✔ persist, should put some more data inside a triple
    1) persist, should return the inserted data


  46 passing (123ms)
  1 failing

  1) a basic triple store
       persist, should return the inserted data:
     Uncaught TypeError: leveldb.createValueStream is not a function
      at Object.getStream (lib/levelgraph.js:59:28)
      at Object.get (lib/utilities.js:47:27)
      at /home/smag/dev/levelgraph/test/persist_properties_spec copy.js:27:10
      at /home/smag/dev/levelgraph/node_modules/abstract-level/abstract-level.js:589:7


```

**Comment by finwo** [comment]
Might be a bit late, but can you confirm the most recent version of levelgraph fixes your use-case since the changes in #199 ?
